### ISSUE TITLE
Access Denied error when using the GetSectionFromStaticMesh in Editor 4.15

### ISSUE THREAD

**Issue by kweeniemike** [Koderz/RuntimeMeshComponent#34] opened 2017-03-07 16:27 UTC
Whenever I try to use the Blueprint Node for GetSectionFromStaticMesh in the Editor, the editor Crashes with the following error:

```
Access violation - code c0000005 (first/second chance not available)
UE4Editor_RuntimeMeshComponent!FRuntimeMeshComponentVerticesBuilder::Reset() [d:\maikel files\unreal projects\clonerruntimecpp\plugins\ue4runtimemeshcomponent\source\runtimemeshcomponent\public\runtimemeshbuilder.h:860]
UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::GetSectionFromStaticMesh() [d:\maikel files\unreal projects\clonerruntimecpp\plugins\ue4runtimemeshcomponent\source\runtimemeshcomponent\private\runtimemeshlibrary.cpp:408]
UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::GetSectionFromStaticMesh() [d:\maikel files\unreal projects\clonerruntimecpp\plugins\ue4runtimemeshcomponent\source\runtimemeshcomponent\private\runtimemeshlibrary.cpp:463]
UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::execGetSectionFromStaticMesh() [d:\maikel files\unreal projects\clonerruntimecpp\plugins\ue4runtimemeshcomponent\source\runtimemeshcomponent\public\runtimemeshlibrary.h:14]
UE4Editor_CoreUObject!UFunction::Invoke() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\coreuobject\private\uobject\class.cpp:4525]
UE4Editor_CoreUObject!UObject::CallFunction() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:721]
UE4Editor_CoreUObject!UObject::ProcessContextOpcode() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2149]
UE4Editor_CoreUObject!UObject::ProcessInternal() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:948]
UE4Editor_CoreUObject!UFunction::Invoke() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\coreuobject\private\uobject\class.cpp:4525]
UE4Editor_CoreUObject!UObject::ProcessEvent() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1318]
UE4Editor_Engine!AActor::ProcessEvent() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\engine\private\actor.cpp:678]
UE4Editor_Engine!AActor::UserConstructionScript()
UE4Editor_Engine!AActor::ProcessUserConstructionScript() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\engine\private\actorconstruction.cpp:841]
UE4Editor_Engine!AActor::ExecuteConstruction() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\engine\private\actorconstruction.cpp:757]
UE4Editor_Engine!AActor::RerunConstructionScripts() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\engine\private\actorconstruction.cpp:490]
UE4Editor_UnrealEd!FReinstanceFinalizer::Finalize() [d:\build\++ue4+release-4.15+compile\sync\engine\source\editor\unrealed\private\kismet2\kismetreinstanceutilities.cpp:523]
UE4Editor_UnrealEd!FBlueprintCompileReinstancer::ReinstanceObjects() [d:\build\++ue4+release-4.15+compile\sync\engine\source\editor\unrealed\private\kismet2\kismetreinstanceutilities.cpp:923]
UE4Editor_UnrealEd!FKismetEditorUtilities::CompileBlueprint() [d:\build\++ue4+release-4.15+compile\sync\engine\source\editor\unrealed\private\kismet2\kismet2.cpp:868]
UE4Editor_Kismet!FBlueprintEditor::Compile() [d:\build\++ue4+release-4.15+compile\sync\engine\source\editor\kismet\private\blueprinteditor.cpp:3283]
UE4Editor_Kismet!TBaseSPMethodDelegateInstance<0,FBlueprintEditor,0,TTypeWrapper<void> __cdecl(void)>::Execute() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:327]
UE4Editor_Kismet!TBaseSPMethodDelegateInstance<0,FBlueprintEditor,0,void __cdecl(void)>::ExecuteIfSafe() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:433]
UE4Editor_Slate!FUICommandList::ExecuteAction() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\slate\private\framework\commands\uicommandlist.cpp:97]
UE4Editor_Slate!SToolBarButtonBlock::OnClicked() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\slate\private\framework\multibox\stoolbarbuttonblock.cpp:305]
UE4Editor_Slate!TMemberFunctionCaller<SToolBarButtonBlock,FReply (__cdecl SToolBarButtonBlock::*)(void) __ptr64>::operator()<>() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\public\delegates\delegateinstanceinterface.h:165]
UE4Editor_Slate!TTupleImpl<TIntegerSequence<unsigned int> >::ApplyAfter<TMemberFunctionCaller<SToolBarButtonBlock,FReply (__cdecl SToolBarButtonBlock::*)(void) __ptr64> >() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\public\delegates\tuple.h:134]
UE4Editor_Slate!TBaseSPMethodDelegateInstance<0,SToolBarButtonBlock,0,FReply __cdecl(void)>::Execute() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:327]
UE4Editor_Slate!TBaseDelegate<FReply>::Execute() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:537]
UE4Editor_Slate!SButton::OnMouseButtonUp() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\slate\private\widgets\input\sbutton.cpp:278]
UE4Editor_Slate!<lambda_8d0e9a1da76abd0a756a3a9d775f5ed1>::operator()() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5075]
UE4Editor_Slate!FEventRouter::Route<FReply,FEventRouter::FToLeafmostPolicy,FPointerEvent,<lambda_8d0e9a1da76abd0a756a3a9d775f5ed1> >() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:238]
UE4Editor_Slate!FSlateApplication::RoutePointerUpEvent() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5064]
UE4Editor_Slate!FSlateApplication::ProcessMouseButtonUpEvent() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5531]
UE4Editor_Slate!FSlateApplication::OnMouseUp() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5508]
UE4Editor_Core!FWindowsApplication::ProcessDeferredMessage() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\private\windows\windowsapplication.cpp:1698]
UE4Editor_Core!FWindowsApplication::DeferMessage() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\private\windows\windowsapplication.cpp:2120]
UE4Editor_Core!FWindowsApplication::ProcessMessage() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\private\windows\windowsapplication.cpp:867]
UE4Editor_Core!FWindowsApplication::AppWndProc() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\private\windows\windowsapplication.cpp:714]
user32
user32
UE4Editor_Core!FWindowsPlatformMisc::PumpMessages() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\core\private\windows\windowsplatformmisc.cpp:980]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\launch\private\launchengineloop.cpp:2977]
UE4Editor!GuardedMain() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\launch\private\launch.cpp:166]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:134]
UE4Editor!WinMain() [d:\build\++ue4+release-4.15+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:210]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264]
kernel32
ntdll
```

All I do when using the node is set the mesh to the Shape_Torus from the Standard Assets and then try to run the program. 

I am using the master branch directly in the plugin folder of the project. Am I doing something extremely wrong here or is this actually an issue?

**Comment by Zinglish** [comment] 2017-03-07 17:21
Can we see a screenshot of your blueprint please?

**Comment by kweeniemike** [comment] 2017-03-07 18:02
The PC I got this error on is in the office, so I don't have access to that until Thursday. Recreated the problem on my own PC, but had to use UE4.14.3 since UE 4.15 is not installed yet. I am installing it right now in case it is needed. 

In the simplest form it already crashes using it like this.
![image](https://cloud.githubusercontent.com/assets/10939460/23670258/718192e0-0367-11e7-9555-7dfc7b9f2384.png)

Simple version of what I was trying out was to recreate the static mesh in a Runtime Mesh Component. 
![image](https://cloud.githubusercontent.com/assets/10939460/23670376/ce85ec8e-0367-11e7-8d24-e836104ae7f2.png)

These blueprints are the same as I was trying in the 4.15 project. For some reason the error came out a bit differently, possibly due to it being 4.14.3 so I am including it below in case it matters.

```
Access violation - code c0000005 (first/second chance not available)

UE4Editor_RuntimeMeshComponent!FRuntimeMeshComponentVerticesBuilder::Reset() [e:\documents\school\git\unreal engine\temp\runtimetest\plugins\runtimemeshcomponent\source\runtimemeshcomponent\public\runtimemeshbuilder.h:860]
UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::GetSectionFromStaticMesh() [e:\documents\school\git\unreal engine\temp\runtimetest\plugins\runtimemeshcomponent\source\runtimemeshcomponent\private\runtimemeshlibrary.cpp:408]
UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::GetSectionFromStaticMesh() [e:\documents\school\git\unreal engine\temp\runtimetest\plugins\runtimemeshcomponent\source\runtimemeshcomponent\private\runtimemeshlibrary.cpp:463]
UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::execGetSectionFromStaticMesh() [e:\documents\school\git\unreal engine\temp\runtimetest\plugins\runtimemeshcomponent\source\runtimemeshcomponent\public\runtimemeshlibrary.h:14]
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll
```

**Comment by Zinglish** [comment] 2017-03-07 19:34
You have to feed `Create Mesh Section` UV1 and Colors arrays, even if they are empty. The crash occurs here: https://github.com/Koderz/UE4RuntimeMeshComponent/blob/master/Source/RuntimeMeshComponent/Public/RuntimeMeshBuilder.h#L860 at which point it's attempting to access a pointer to `Colors` (And later `UV1`) but since you provided no such pointer input in your Blueprint.

**Comment by kweeniemike** [comment] 2017-03-09 08:46
Ok I tried to do what you suggested, but it still isn't working. This is on 4.15 again.

![image](https://cloud.githubusercontent.com/assets/10939460/23741971/476a7a4a-04ab-11e7-9b72-1c3ad2a81393.png)

This code creates correct empty arrays of the correct size, as suggested by the tooltip on the UV1 and Colors input nodes. It still crashes with the exact same error.

So a couple of questions I have:
- The tooltips for UV1 and Colors boths mention that they are optional. So why would this cause a problem?
- The problem occurs on GetSectionFromStaticMesh, seeinig from the errors, so it doesn't reach CreateMeshSection, so why would this cause it?

To me it seems GetSectionFromStaticMesh is not working, seeing as even without touching CreateMeshSection it already causes the editor to crash.

**Comment by Moddingear** [comment] 2017-04-04 10:09
I am also having the same issue, and the crash is caused by GetSectionFromStaticMesh.

**Comment by fhareide** [comment] 2017-06-30 22:32
I am having the exact same issue. Also happens when I try to use the same method from C++. Any news on this? The error in VS says something about this->Color() being a nullptr.

Any help is much appreciated.

**Comment by Koderz** [comment] 2018-02-11 01:20
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz

**Closed by Koderz** 2018-02-11 01:20 UTC
