### ISSUE TITLE
How can I hit RMC in mobile?

### ISSUE THREAD

**Issue by ToniFF** [Koderz/RuntimeMeshComponent#92] opened 2018-04-12 03:16 UTC
There is no collision for RMC in mobile, but I really need functions called when I touch RMCs.

**Comment by ToniFF** [comment] 2018-04-12 03:35
I try to store the transform of section when created, but I can't get the transform.

**Comment by Koderz** [comment] 2018-06-20 14:53
Hey @ToniFF,

For mobile you'd need to make sure to include the RuntimePhysXCooking module in the build.cs file for it to work on mobile. I'll be closing this issue as it should be working as intended, if you have additional issues, please feel free to open a new issue!

**Closed by Koderz** 2018-06-20 14:53 UTC
