### ISSUE TITLE
Error when calling CreateMeshSection

### ISSUE THREAD

**Issue by dazotaro** [Koderz/RuntimeMeshComponent#166] opened 2020-05-06 19:37 UTC
Hi,

I am using UE4 version 4.24.3, and the latest version of this plugin. I have included  "RuntimeMeshComponent.h" in my header file, and added "RuntimeMeshComponent" to the build file, as in 

    PublicDependencyModuleNames.AddRange(..., "RuntimeMeshComponent" };

I create a RuntimeMeshComponent with 

    UPROPERTY(VisibleAnywhere)
    URuntimeMeshComponent * mesh;

And in the constructor of my actor, I do

    mesh = CreateDefaultSubobject<URuntimeMeshComponent>(TEXT("TestMesh"));
    RootComponent = mesh;

In another function, when I call CreateMeshSection on an element of type RuntimeMeshComponent. 

    TArray<FVector> Vertices;
    TArray<FVector> Normals;
    TArray<FRuntimeMeshTangent> Tangents;
    TArray<FVector2D> TextureCoordinates;
    TArray<int32> Triangles;
    TArray<FColor> Colors;
    ...
    ...
    mesh->CreateMeshSection(0, Vertices, Triangles, Normals, TextureCoordinates, Colors, Tangents, true);

the following compilation error occurs

    error: no member named 'CreateMeshSection' in 'URuntimeMeshComponent'
    mesh->CreateMeshSection(0, Vertices, Triangles, Normals, TextureCoordinates, Colors, Tangents, true);

What am I missing? I have search the header files in the plugin, but I don't see a reference to `CreateMeshSection`.

Any help will be greatly appreciated,

Thanks

**Comment by Moddingear** [comment] 2020-05-06 19:41
Duplicate of issue #165 , if you want V3-like use just use the RuntimeMeshComponentStatic

**Closed by Moddingear** 2020-05-06 19:41 UTC

**Comment by dazotaro** [comment] 2020-05-06 19:47
So the best way to learn to use this plugin is the RuntimeMeshComponent-Examples project?

Thanks for your help

**Comment by Moddingear** [comment] 2020-05-06 19:50
That and the discord

**Comment by dazotaro** [comment] 2020-05-06 19:52
Excellent. Thanks
